### ISSUE TITLE
Mod can't connect to the its own server

### ISSUE THREAD

**Issue by cyb3rm4n** [tiffit/Wynnforge#4]
Go the message about wynnforge server is unaviabl,e also got this logs in console: 

[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:913)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at com.google.gson.Gson.fromJson(Gson.java:887)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at com.google.gson.Gson.fromJson(Gson.java:852)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at com.google.gson.Gson.fromJson(Gson.java:801)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at com.google.gson.Gson.fromJson(Gson.java:773)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at net.tiffit.wynnforge.data.WynnforgeServerConnector.getKey(WynnforgeServerConnector.java:62)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at net.tiffit.wynnforge.data.WynnforgeServerConnector.connectWynnforgeServer(WynnforgeServerConnector.java:30)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at net.tiffit.wynnforge.Wynnforge.finishLoad(Wynnforge.java:121)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[19:16:18] [main/INFO] [STDERR]: [net.tiffit.wynnforge.data.WynnforgeServerConnector:getKey:67]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by tiffit** [comment]
Server has been deprecated and removed entirely in the latest version (0.3.2)
